@baseUrl = http://localhost:4000/v1

###

# @name healcheck
GET {{baseUrl}}/healthcheck
Content-Type: application/json

###

# @name create_movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
"title": "Moana",
"year": 2016,
"runtime": "107 mins",
"genres": ["animation", "adventure"]
}

###

# @name get_movie
GET {{baseUrl}}/movies/:id
Content-Type: application/json