version: '3.8'
name: greenlight

services:
  database:
    container_name: greenlight-db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: greenlight
    volumes:
    - ./.infra/init.sql:/docker-entrypoint-initdb.d/init.sql
      